# Backend
backend = "glx";
vsync = true;
glx-no-stencil = true;
use-damage = true;

# Corner radius
corner-radius = 0;

# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.6;
shadow-color = "#000000";

shadow-exclude = [
    "name = 'polybar'",
    "name = 'Notification'",
    "class_g = 'Conky'",
    "class_g ?= 'Notify-osd'",
    "class_g = 'Cairo-clock'",
    "class_g = 'Bspwm'",
    "class_i = 'presel_feedback'",
    "_GTK_FRAME_EXTENTS@:c",
];

# Opacity
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
    "10:class_g = 'Bspwm'",
    "10:class_i = 'presel_feedback'",
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
fade-exclude = [];

# Window type settings
wintypes:
{
    popup_menu = { opacity = 1.0; };
    dropdown_menu = { opacity = 1.0; };
    dnd = { shadow = false; };
    dock = { shadow = false; };
    tooltip = { fade = true; shadow = true; opacity = 1.0; focus = true; };
};
